---
resources:
  - name: git
    type: git
    source: 
      uri: https://github.com/seveas/concourse-copr-resource.git
      branch: master

  - name: docker
    type: docker-image
    source:
      repository: seveas/concourse-copr-resource
      tag: latest
      username: ((docker-username))
      password: ((docker-password))

jobs:
  - name: publish
    plan:
      - get: git
        trigger: true
      - put: docker
        params:
          build: git
